// Topologias pré-fabricadas que o utilizador insere no canvas.
// Cada `gen()` devolve { nodes, connections } prontos a fundir no diagrama.
import { uid } from "../lib/uid.js";
import { LAYER_KEYS } from "./camadas.js";

export const TEMPLATES = [
  { id:"helicoidal", name:"Helicoidal",      icon:"🌀", desc:"Espiral L1→L2→L3→L4→L5",             gen:()=>{ const ns=LAYER_KEYS.map((l,i)=>({id:`node_${uid()}`,layer:l,x:80+i*130,y:200+Math.sin(i*1.2)*60,createdAt:Date.now()})); return {nodes:ns,connections:ns.slice(0,-1).map((n,i)=>({id:`conn_${uid()}`,sourceId:n.id,targetId:ns[i+1].id}))}; }},
  { id:"anel",       name:"Anel de Controle",icon:"⭕", desc:"Loop completo com retorno L5→L2",       gen:()=>{ const cx=300,cy=220,r=110; const ns=LAYER_KEYS.map((l,i)=>{const a=(i/5)*Math.PI*2-Math.PI/2;return{id:`node_${uid()}`,layer:l,x:cx+Math.cos(a)*r,y:cy+Math.sin(a)*r,createdAt:Date.now()}}); return {nodes:ns,connections:[...ns.slice(0,-1).map((n,i)=>({id:`conn_${uid()}`,sourceId:n.id,targetId:ns[i+1].id})),{id:`conn_${uid()}`,sourceId:ns[4].id,targetId:ns[1].id}]}; }},
  { id:"paralelo",   name:"Ciclos Paralelos",icon:"⚡", desc:"L2 com dois ramos em paralelo",          gen:()=>{ const l1={id:`node_${uid()}`,layer:"L1",x:150,y:220,createdAt:Date.now()},l2={id:`node_${uid()}`,layer:"L2",x:280,y:220,createdAt:Date.now()},a1={id:`node_${uid()}`,layer:"L3",x:410,y:140,createdAt:Date.now()},a2={id:`node_${uid()}`,layer:"L3",x:410,y:300,createdAt:Date.now()},b1={id:`node_${uid()}`,layer:"L4",x:540,y:140,createdAt:Date.now()},b2={id:`node_${uid()}`,layer:"L4",x:540,y:300,createdAt:Date.now()},c1={id:`node_${uid()}`,layer:"L5",x:670,y:140,createdAt:Date.now()},c2={id:`node_${uid()}`,layer:"L5",x:670,y:300,createdAt:Date.now()}; return {nodes:[l1,l2,a1,a2,b1,b2,c1,c2],connections:[{id:`conn_${uid()}`,sourceId:l1.id,targetId:l2.id},{id:`conn_${uid()}`,sourceId:l2.id,targetId:a1.id},{id:`conn_${uid()}`,sourceId:l2.id,targetId:a2.id},{id:`conn_${uid()}`,sourceId:a1.id,targetId:b1.id},{id:`conn_${uid()}`,sourceId:a2.id,targetId:b2.id},{id:`conn_${uid()}`,sourceId:b1.id,targetId:c1.id},{id:`conn_${uid()}`,sourceId:b2.id,targetId:c2.id},{id:`conn_${uid()}`,sourceId:c1.id,targetId:l2.id},{id:`conn_${uid()}`,sourceId:c2.id,targetId:l2.id}]}; }},
  { id:"estrela",    name:"Estrela",         icon:"✦", desc:"Hub L2 com L1s e L3s radiais",           gen:()=>{ const hub={id:`node_${uid()}`,layer:"L2",x:300,y:220,createdAt:Date.now()}; const inp=[0,1,2].map(i=>{const a=(i/3)*Math.PI*2-Math.PI/2;return{id:`node_${uid()}`,layer:"L1",x:300+Math.cos(a)*130,y:220+Math.sin(a)*130,createdAt:Date.now()}}); const out=[0,1,2].map(i=>{const a=(i/3)*Math.PI*2-Math.PI/6;return{id:`node_${uid()}`,layer:"L3",x:300+Math.cos(a)*130,y:220+Math.sin(a)*130,createdAt:Date.now()}}); return {nodes:[hub,...inp,...out],connections:[...inp.map(n=>({id:`conn_${uid()}`,sourceId:n.id,targetId:hub.id})),...out.map(n=>({id:`conn_${uid()}`,sourceId:hub.id,targetId:n.id}))]}; }},
];
